---
title: "Egzamin (pierwszy termin) - Programowanie Strukturalne - Zestaw J01"
lang: pl
output:
  word_document: default
  pdf_document: default
---

*Zadanie 1 i 2: po 10 pkt. Zadanie 3 i 4: po 15 pkt.*

*Punktacja: 46-50 pkt - bdb(5,0); 41-45 pkt - db+(4,5); 36-40 pkt - db(4,0); 31-35 pkt - dst+(3,5); 26-30 pkt - dst(3,0); 0-25 pkt - ndst (2,0).* 

Zad.1. W folderze DebugJ01 znajduje się projekt z kodem w języku C. W pliku main.c w niektórych linijkach są komentarze. Twoim zadaniem jest wpisanie wartości odpowiednich zmiennych po wykonaniu konkretnej linii kodu. Dopisanie nowych linijek i instrukcji poza komentarzami będzie powodowało 0 pkt. Zmienne będące adresami muszą obowiązkowo być w systemie szesnastkowym.

Zad.2. Napisz funkcję, która otrzymuje cztery argumenty: dodatnią liczbę całkowitą $n$, $n$-elementowe tablice `tab1` i `tab2` oraz $2\cdot n$-elementową tablicę `tab3` o elementach typu `int`. Funkcja powinna ustawić elementy tak, aby na początku tablicy tab3 powinny się znaleźć elementy tablicy `tab2`, a po nich elementy będące różnicą poszczególnych elementów tablicy `tab1` i `tab2`. Stwórz dwa przypadki testowe.

Zad.4. Napisz funkcję, która porównuje dwie listy bez głowy o elementach typu:

```c
struct node {
    int x;
    struct node * next;
};
```

i zwraca 1 jeśli suma sześcianów elementów nieparzystych na obu listach jest równa oraz 0 w pozostałych przypadkach. Stwórz jeden przypadek testowy.

Zad.4. Napisz funkcję, której argumentem jest dwuwymiarowa tablica tablic i jej wymiary $n$ i $m$. Funkcja ma stworzyć dynamiczną $n\cdot m$ elementową tablicę jednowymiarową powstałą z przepisanie kolejno wierszami elementów tablicy będącej argumentem funkcji. Funkcja ma zwrócić wskaźnik do nowo utworzonej tablicy. Stwórz przypadek testowy.
