---
title: "Egzamin (pierwszy termin) - Programowanie Strukturalne - Zestaw J13"
lang: pl
output:
  word_document: default
  pdf_document: default
---

*Zadanie 1 i 2: po 10 pkt. Zadanie 3 i 4: po 15 pkt.*

*Punktacja: 46-50 pkt - bdb(5,0); 41-45 pkt - db+(4,5); 36-40 pkt - db(4,0); 31-35 pkt - dst+(3,5); 26-30 pkt - dst(3,0); 0-25 pkt - ndst (2,0).* 

Zad.1. W folderze PoprawJ13 znajduje się kod w języku C, który nie spełnia zasad kompilacji. Popraw kod modyfikując dokładnie 1 linijkę tak, aby się kompilował. Zabronioną operacją jest komentowanie kodu. Do zmodyfikowanych linii zaliczają się zarówno linie istotne ze względu na kompilację jak i te nieistotne (np. dodanie spacji przed operatorem może być operacją nieistotną ze względu na kompilację, ale będzie liczone jako zmodyfikowana linijka).

Zad.2. Napisz funkcję, która otrzymuje cztery argumenty: dodatnią liczbę całkowitą $m$, liczbę całkowitą $n$ oraz dwie $m$-elementowe tablice `tab1` i `tab2` o elementach typu `int`. Funkcja ma zwrócić liczbę ile liczb większych niż $n$ jest w tablicy `tab1` i `tab2`. Stwórz dwa przypadki testowe dla funkcji.

Zad.3. Napisz funkcję, której argumentem jest dwuwymiarowa tablica tablic i jej wymiary $n$ i $m$. Funkcja ma zadanie odwrócić elementy tablicy z osobna w każdym wierszu. Stwórz przypadek testowy.

Zad.4. Napisz funkcję, która otrzymuje jako argument listę bez głowy o elementach typu:

```c
struct node {
    int w;
    struct node * next;
};
```
Funkcja ma usunąć z listy wszystkie elementy nieparzyste. Stwórz przypadek testowy.
